### ISSUE TITLE
Inconsistency in r4 configuration data.exch2

### ISSUE THREAD

**Issue by emmomp** [ECCO-GROUP/ECCO-v4-Configurations#140]
The [data.exch2 file](https://github.com/ECCO-GROUP/ECCO-v4-Configurations/blob/18dc4800614d3d7c247dec4984f03aafeccf9812/ECCOv4%20Release%204/namelist/data.exch2) in the Release 4 branch is inconsistent with the same file in input_init/NAMELIST on the NASA drive (I accessed it via https://podaac.jpl.nasa.gov/dataset/ECCO_L4_ANCILLARY_DATA_V4R4) and appears to be missing three entries in the blank list for the 15x15 (360 core) configuration. I believe the NASA version is correct as it has 108 entries whereas the version in this repo has 105, and is missing 188, 242 and 376.

From this repository:
>#15x15   nprocs = 360
>#blankList(1:108)=1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,21,22,23,24,
>#65,71,75,76,90,95,96,101,102,109,110,111,112,113,114,115,116,117,118,119,
>#120,121,122,123,124,125,126,127,128,129,130,131,132,
>#189,190,193,194,195,196,199,
>#200,201,202,203,205,206,207,208,209,211,212,213,214,215,216,247,253,
>#267,268,269,270,287,288,305,306,323,324,341,342,359,360,362,377,378,
> #380,381,382,395,396,400,412,413,414,430,

From the NASA drive:
>#15x15   nprocs = 360
>#blankList(1:108)=1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,21,22,23,24,
>#65,71,75,76,90,95,96,101,102,109,110,111,112,113,114,115,116,117,118,119,
>#120,121,122,123,124,125,126,127,128,129,130,131,132,
>#188,189,190,193,194,195,196,199,
>#200,201,202,203,205,206,207,208,209,211,212,213,214,215,216,242,247,253,
>#267,268,269,270,287,288,305,306,323,324,341,342,359,360,362,376,377,378,
>#380,381,382,395,396,400,412,413,414,430,

**Comment by emmomp** [comment]
This seems to be deliberate as it was introduced in a commit by @owang01 https://github.com/ECCO-GROUP/ECCO-v4-Configurations/commit/a9a38c0c5da38648cf7fb6e843d0d1ca56ca5347

Am I missing something else? When I try to run as is (without 188, 242 and 376) I get the error "Domain Total # of tiles =   468 does not match (SIZE.h+blankList)=   465"

**Comment by owang01** [comment]
@emmomp The files in this repository will be kept being updated, while those hosted by the PO.DAAC (or the NASA drive as you called) are frozen. So when there is difference, use files in this repository.  

This version of data.exch2 (without 188, 242 and 376) is deliberate. @jahn pointed out that with the three tiles he got unconnected-points warnings and the results diverge near those unconnected-points. The pull request #105 (commit ommit https://github.com/ECCO-GROUP/ECCO-v4-Configurations/commit/a9a38c0c5da38648cf7fb6e843d0d1ca56ca5347) reflects this change.

Regarding the error "Domain Total # of tiles = 468 does not match (SIZE.h+blankList)= 465", I suspect the variable "nPx" is still set to 360 in your SIZE.h. If so, please change it to 363 and recompile the code. I believe this will fix the error. 

I just have a new pull request #152 that changes "blankList(1:108)" in data.exch2 to "blankList(1:105)". However, this bug is benign. The model states before and after the fix are identical.
